.TH NENE "1" "July 2025" "nene v1.4.32-nightly" "User Commands"
.SH NAME
nene \- manual page for nene v1.4.32-nightly
.SH DESCRIPTION
Nene is both a static site and a set of Bash tools you can run straight from your terminal
Usage :
.TP
\fB\-a\fR    \fB\-\-api\-termux\fR
Install nene\-ak47.sh into \fI\,~/bin\/\fP for Run nene's app via Android Share
.TP
\fB\-u\fR    \fB\-\-select\-url\fR
Select and open the link.
.HP
\fB\-s\fR    \fB\-\-select\fR=\fI\,[apps]\/\fR Execute the explicitly specified application.
.HP
\fB\-m\fR    \fB\-\-mode\fR=\fI\,[online]\/\fR Select and run through the link.
.TP
\fB\-v\fR    \fB\-\-version\fR
Print version script.
.TP
\fB\-h\fR    \fB\-\-help\fR
Print this message.
.SH "SEE ALSO"
The full documentation for
.B nene
is maintained as a Texinfo manual.  If the
.B info
and
.B nene
programs are properly installed at your site, the command
.IP
.B info nene
.PP
should give you access to the complete manual.
