name: Sync Package Files

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Prepare directories
        run: |
          mkdir -p data/data/com.termux/files/usr/bin
          mkdir -p data/data/com.termux/files/usr/libexec
          mkdir -p data/data/com.termux/files/usr/share/man/man1
          mkdir -p data/data/com.termux/files/usr/share/doc/nene
          mkdir -p data/data/com.termux/files/usr/share/bash-completion/completions

      - name: Sync package files
        run: |
          cp bin/nene \
            data/data/com.termux/files/usr/bin/nene
          cp bin/nene-setup.sh \
            data/data/com.termux/files/usr/bin/nene-setup.sh

          cp not-echo-not-true.py \
            data/data/com.termux/files/usr/libexec/not-echo-not-true.py

          cp completions/nene.completions.bash \
            data/data/com.termux/files/usr/share/bash-completion/completions/nene

          gzip -9 -c man/nene.1 \
            > data/data/com.termux/files/usr/share/man/man1/nene.1.gz

          cp LICENSE \
            data/data/com.termux/files/usr/share/doc/nene/LICENSE

          cp README.md \
            data/data/com.termux/files/usr/share/doc/nene/README.md

          chmod 755 data/data/com.termux/files/usr/bin/nene
          chmod 755 data/data/com.termux/files/usr/bin/nene-setup.sh

      - name: Debug Git Status
        run: |
          git status

      - name: Commit changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          git add data/

          git commit -m "Sync package files" || echo "No changes to commit"

      - name: Push changes
        run: |
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} HEAD:${GITHUB_REF#refs/heads/}
