name: Sync not-echo-not-true.py

on:
  push:
    branches:
      - master

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Copy file
        run: |
          cp not-echo-not-true.py libexec/not-echo-not-true.py

      - name: Debug - Check Git Status
        run: git status

      - name: Commit changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add libexec/not-echo-not-true.py
          git commit -m "Sync not-echo-not-true.py to libexec/not-echo-not-true.py" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} HEAD:${{ github.ref }}
          
